#!/bin/sh

###############################################################
# DECODER RUNNER
# H264 decoder

# Set name of terminal
PS1=$
PROMPT_COMMAND=
echo -en "\033]0;DECODER TERMINAL\a"

echo "RUNNER: Starting Decoder."
docker run --rm -ti --net=host --ipc=host -e DISPLAY=$DISPLAY -v /tmp:/tmp h264decoder:v0.0.5 --cid=253 --name=img

